title:             ShouKai-Blog
email:             huangshoukai@yeah.net
description:       人生在于体会，今时哪及昔时。
author:            shoukai
baseurl:           ""
url:               "http://shoukai.github.io"

# Social Profiles
github_username:   shoukai
weibo_username:    3480000900

# Build settings
markdown:          kramdown
highlighter:       rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

liquid:
  error_mode: warn

kramdown:
  input:          GFM
  auto_ids:       true
  hard_wrap:      false
  extensions:
    - autolink
    - footnotes
    - smart
