# Site settings
title: ShouKai
SEOTitle: ShouKai Blog
header-img: "skblog.duiduiche.com/8dfb1b86212935379ada7e13483f27d4.jpg"
email: huangshoukai@yeah.net
description: 人生在于体会，今时哪及昔时。
keyword: ""
baseurl: ""
url: "http://shoukai.github.io"


# SNS settings
RSS: false
weibo_username:     3480000900
#zhihu_username:     huxpro
github_username:   shoukai
#twitter_username:  huxpro
#facebook_username:  huxpro
douban_username:  74214055


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: rouge


# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
# TODO duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
# TODO duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 70280fa191231708a092ffd9ecad59ec
# Google Analytics
# TODO ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# TODO ga_domain: shoukai.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "读书，旅行，总有一个在路上"
sidebar-avatar: http://skblog.duiduiche.com/ab560058fbcb36657b56eee62f7fd79a.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

